### ISSUE TITLE
Switching the active device by Car Thing

### ISSUE THREAD

**Issue by vakst** [usenocturne/nocturne-ui#59] opened 2024-12-13 18:39 UTC
If you have 1+ devices and use physical buttons on the top to start playing the playlist, then Car Thing switch your active device to the first one (regardless of active/not active) from the list in endpoint https://api.spotify.com/v1/me/player/devices

Example:

```
{
  "devices": [
    {
      "id": "1111",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Web Player (Chrome)",
      "supports_volume": true,
      "type": "Computer",
      "volume_percent": 100
    },
    {
      "id": "2222",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "KF",
      "supports_volume": false,
      "type": "Tablet",
      "volume_percent": 100
    },
    {
      "id": "3333",
      "is_active": true,
      "is_private_session": false,
      "is_restricted": false,
      "name": "I",
      "supports_volume": false,
      "type": "Smartphone",
      "volume_percent": 100
    },
    {
      "id": "4444",
      "is_active": false,
      "is_private_session": false,
      "is_restricted": false,
      "name": "Web Player (Chrome)",
      "supports_volume": true,
      "type": "Computer",
      "volume_percent": 100
    }
  ]
}
```

In this case, the active device was 3333, but after pushing a top button on Car Thing the active device was switched to 1111

How to fix it? Choose the active device instead of the first one:
https://github.com/usenocturne/nocturne-ui/blob/5c8a21e288566b6bec11eec3d0cf3843aa9d13bc/src/pages/playlist/%5BplaylistId%5D.jsx#L319

**Comment by itsnebulalol** [comment] 2024-12-14 19:21
Duplicate of #21. Please leave this as a comment on that issue as it is helpful nonetheless.

**Comment by vakst** [comment] 2024-12-14 19:44
It's not a feature that is described in #21. It's a bug.  I fixed it in https://github.com/usenocturne/nocturne-ui/pull/60

**Comment by itsnebulalol** [comment] 2024-12-14 19:48
Right, I see. I misread, will open this again so it’ll get closed when the PR is merged.

**Closed** 2024-12-19 00:34 UTC
